### ISSUE TITLE
bower install fails

### ISSUE THREAD

**Issue by weatherbell** [seaneking/sticky-element#1]
Attempting to install this package through bower causes an error:

> bower Stickyfill#master        ECMDERR Failed to execute "git ls-remote --tags --heads https://github.com/seaneking/stickyfill.git", exit code of #128 remote: Repository not found. fatal: Authentication failed for 'https://github.com/seaneking/stickyfill.git/'
> 
> Additional error details:
> remote: Repository not found.
> fatal: Authentication failed for 'https://github.com/seaneking/stickyfill.git/'
>

**Comment by seaneking** [comment]
Ah, sorry, accidentally removed that forked repo - reinstated, should be working now.

**Comment by crysxyh** [comment]
Hi seaneking,

I am trying to install highcharts with bower.  However, I am getting same error mentioned in this issue.

`bower Stickyfill#master                      ECMDERR Failed to execute "git ls-remote --tags --heads https://github.com/seaneking/stickyfill.git", exit code of #128 remote: Repository not found. fatal: repository 'https://github.com/seaneking/stickyfill.git/' not found`.

I am wondering if you can put the forked repo back again.

Thanks a lot!
